contact/urls.py
from django.urls import path
from contact import views

app_name = 'tennisTracer'    

urlpatterns = [
    
    path('tennisTracer/', views.index, name='index'), #Alterar posteriormente
    path('tennisTracer/<int:contact_id>/', views.profile, name='profile'),

    path('tennisTracer/', views.profile, name='profile'),
    # Crud 
    # Create: Criar 
    path('tennisTracer/createTemas/', views.createTemaAula, name='createTemas'),
    path('tennisTracer/createAluno/', views.createAluno, name='createAluno'),
    path('tennisTracer/addAluno/<int:id>/', views.addAluno, name='addAluno'),
    path('tennisTracer/vinAluno/', views.vinAluno, name='vinAluno'),
    path('tennisTracer/aula/<int:aula_id>/alunos/', views.alunos_por_aula, name='alunos_por_aula'),
    path('tennisTracer/aula/presente/', views.registrar_presenca, name='registrar_presenca'),

    # Detail: Get
    path('tennisTracer/profileCoach/', views.profileCoach, name='profileCoach'),
    # Update: Atualizar
    # Delete
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User



class Coach(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return f'{self.name}'
    
class Aluno(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    old = models.IntegerField()  # Usar IntegerField para idade
    phone = models.CharField(blank=True, null=True, max_length=50)
    login = models.CharField(max_length=50)
    birthday = models.DateField(blank=True, null=True)
    created_in = models.DateTimeField(default=timezone.now)
    obs = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, null=True, upload_to='pictures/')
    category = models.CharField(max_length=50, blank=True)
    owner = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL,
        blank=True, null=True
    )
    coach = models.ForeignKey(
        Coach, 
        on_delete=models.SET_NULL,
        blank=True, null=True
    )

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

class Aula(models.Model):
    day = models.CharField(max_length=50)
    hora_ini = models.TimeField()
    hora_fim = models.TimeField()
    coach = models.ForeignKey(
        Coach, 
        on_delete=models.SET_NULL,
        blank=True, null=True
    )
    
    def __str__(self) -> str:
        return f'{self.id} {self.day} {self.hora_ini} {self.coach} '

class OcorrenciaAula(models.Model):
    aula = models.ForeignKey(Aula, on_delete=models.CASCADE)
    data = models.DateField()
    alunos_presentes = models.ManyToManyField('Aluno', through='Aluno_OcorrenciaAula') 

    def __str__(self) -> str:
        return f'{self.aula} em {self.data}'

class Aluno_OcorrenciaAula(models.Model):
    aluno = models.ForeignKey(Aluno, on_delete=models.CASCADE)
    ocorrenciaAula = models.ForeignKey(OcorrenciaAula, on_delete=models.CASCADE)
    presente = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.aluno} em {self.ocorrenciaAula}'

class Aluno_Aula(models.Model):
    aula = models.ForeignKey(Aula, on_delete=models.SET_NULL, null=True)  
    aluno = models.ForeignKey(Aluno, on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return f'{self.id} {self.aula} {self.aluno}'

class Tema(models.Model):
    tema_name = models.CharField(max_length=250)
    
    def __str__(self) -> str:
        return f'{self.id} {self.tema_name}'

contact/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models
from django.contrib.auth.models import User
from .models import Aluno

class CreateTemaAula(forms.ModelForm):
    
    #### Em um Form, atualiza As info Html do mesmo; 
    tema_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
             'placeholder': 'Digite aqui'
            }
        ),
        label='Informe a Descrição do tema:',
        help_text='Ex: BackHand'
    )

    class Meta:
        model = models.Tema
        fields = (
            'tema_name',
        )
        
        widgets = {
            'tema_name': forms.TextInput(
                
            )
        }

class CreateAluno(forms.ModelForm):

    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Digite o nome'
            }
        ),
        label='Nome Do Aluno',
        help_text='Ex: Camila'
    )

    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Digite o sobrenome'
            }
        ),
        label='Sobrenome do Aluno:',
        help_text='Ex: Oliveira'
    )

    old = forms.CharField(
        widget=forms.NumberInput(
            attrs={
                'placeholder': 'Informe a idade do aluno'
            }
        ),
        label='Idade:',
        help_text='Ex: 4'
    )

    birthday = forms.DateField(
        widget=forms.DateInput(
            format='%d/%m/%Y',  # Formato brasileiro
            attrs={
                'placeholder': 'dd/mm/aaaa',  # Formato de data esperado
                'type': 'text'  # Muda para 'text' para exibir o formato personalizado
            }
        ),
        label='Data de Nascimento',
        help_text='Ex: 31/12/2000'
    )

    login = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Digite o Login'
            }
        ),
        label='Login:',
        help_text='Ex: camila.oliveira'
    )

    owner = forms.ChoiceField(
        choices=[(user.id, user.username) for user in User.objects.all()],
        widget=forms.Select(
            attrs={
                'class': 'form-group',
                'placeholder': 'Escolha'
            }
        ),
        label='Escolha o Tipo do Usuário:',
        help_text='Escolha uma das opções'
    )

    def clean_owner(self):
        owner_id = self.cleaned_data.get('owner')

        # Verifica se o usuário com o ID existe
        try:
            owner = User.objects.get(id=owner_id)
        except User.DoesNotExist:
            raise ValidationError('Usuário inválido.')

        return owner

    class Meta:
        model = models.Aluno  # Associa o formulário ao modelo Aluno
        fields = ('first_name', 'last_name', 'old' , 'login', 'owner')
    
class AddAluno(forms.Form):
    aluno = forms.ModelChoiceField(
        queryset= Aluno.objects.all(),
        widget= forms.Select(
            attrs={
                'class': 'form-control'
            }
        ),
        label='Selecione o Aluno'
    )

contact/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(
        request, 
        'contact/index.html',
    )

contact/views/alunos.py
from contact.models import *
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator


def index(request):
    title = 'Aulas'

    # Obter as aulas do coach específico
    aulas = Aula.objects.filter(coach=1)

    # Paginar as aulas
    paginator = Paginator(aulas, 9)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    # Contexto atualizado para passar os alunos relacionados a cada aula
    context = {
        'title': title,
        'page_obj': page_obj,
    }

    return render(
        request,
        'tennisTracer/day.html',
        context,
    )

def profile(request, contact_id):
    title = 'Perfil'
    aluno = get_object_or_404(Aluno, pk=contact_id)
    # aluno = Aluno.objects.get(pk=contact_id)
    context = {
        'title': title,
        'aluno': aluno
    }

    return render(
        request, 
        'tennisTracer/createdAluno.html',
        context,
    )

# def profile(request):
#     title = 'Perfil'
#     aluno = get_object_or_404(Aluno, pk=contact_id)
#     # aluno = Aluno.objects.get(pk=contact_id)
#     context = {
#         'title': title,
#         'aluno': aluno
#     }

#     return render(
#         request, 
#         'tennisTracer/createdAluno.html',
#         context,
#     )

contact/views/alunos_forms.py
from contact.models import *
from django.shortcuts import get_object_or_404, render, redirect
from contact.forms import CreateTemaAula, CreateAluno, AddAluno
from django.http import JsonResponse
import json


def createTemaAula(request):
    if request.method == 'POST':

        title = 'Cadastrar Nova Aula'
        form = CreateTemaAula(request.POST)

        context = {
            'title': title,
            'form': form
        }

        if form.is_valid():
            form.save()
            return redirect('tennisTracer:createTemas')
        
        return render(
            request, 
            'tennisTracer/createTemaAula.html',
            context,
        )

    title = 'Cadastrar Nova Aula'

    context = {
        'title': title,
        'form': CreateTemaAula
    }

    return render(
        request, 
        'tennisTracer/createTemaAula.html',
        context,
    )

def createAluno(request):
    if request.method == 'POST':

        title = 'Cadastrar Novo Aluno'
        form = CreateAluno(request.POST)
        
        context = {
            'title': title,
            'form': form
        }

        if form.is_valid():
            
            form.save()
            return redirect('tennisTracer:createAluno')

        return render(
            request, 
            'tennisTracer/createAluno.html',
            context,
        )

    title = 'Cadastrar Novo Aluno'
    form = CreateAluno()

    context = {
        'title': title,
        'form': form
    }

    return render(
        request, 
        'tennisTracer/createAluno.html',
        context,
    )

def addAluno(request, id):
    aula = get_object_or_404(Aula, id=id)
    alunos = Aluno.objects.all()

    if request.method == 'POST':
        form = AddAluno(request.POST)

        context = {
        'aula': aula,
        'alunos': alunos,
        'id': id
    }
    
        if form.is_valid():
           aluno = form.cleaned_data['aluno']
           Aluno_Aula.objects.create(aula=aula, aluno=aluno)
           return redirect('tennisTracer:index', id=id)
    
    form = AddAluno()
    print(id)

    context = {
        'form': form,
        'aula': aula,
        'alunos': alunos,
        'id': id
    }
    return render(
        request,
        'tennisTracer/teste.html', 
        context
        )

def vinAluno(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        aula_id = data.get('aula_id')
        aluno_id = data.get('aluno_id')

        aula = get_object_or_404(Aula, id=aula_id)
        aluno = get_object_or_404(Aluno, id=aluno_id)

        # Verifica se a relação já existe para evitar duplicatas
        vinculo_existente = Aluno_Aula.objects.filter(aula=aula, aluno=aluno).exists()

        if not vinculo_existente: 
            Aluno_Aula.objects.create(aula=aula, aluno=aluno)
            return JsonResponse({'status': 'success'}, status=200)
        else:
            return JsonResponse({'status': 'duplicate'}, status=400)
    
    return JsonResponse({'status': 'invalid method'}, status=405)


def detalhes_aula(request, aula_id):
    # Buscar a aula específica
    aula = get_object_or_404(Aula, id=aula_id)
    
    # Buscar os alunos vinculados a essa aula
    alunos_aula = Aluno_Aula.objects.filter(aula=aula)
    
    context = {
        'aula': aula,
        'alunos_aula': alunos_aula,
    }
    
    return render(request, 'day.html', context)

def alunos_por_aula(request, aula_id):
    aula = get_object_or_404(Aula, id=aula_id)
    alunos_aula = Aluno_Aula.objects.filter(aula=aula)


    alunos = []
    for aluno_aula in alunos_aula:
        aluno = aluno_aula.aluno
        alunos.append({
            'id': aluno.id,
            'first_name': aluno.first_name,
            'last_name': aluno.last_name,
            'picture': aluno.picture.url if aluno.picture else None
        })

    return JsonResponse({'alunos': alunos})

def registrar_presenca(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        aula_id = data.get('aula_id')
        alunos_ids = data.get('alunos', [])
        data_ocorrencia = data.get('data_ocorrencia') 
        try:
            # Verificar se a aula existe
            aula = Aula.objects.get(id=aula_id)
            
            # Verificar se já existe uma ocorrência da aula na data informada
            ocorrencia, created = OcorrenciaAula.objects.get_or_create(
                aula=aula,
                data=data_ocorrencia  # Data da aula
            )

            # Para cada aluno selecionado, atualizar ou criar a presença
            for aluno_id in alunos_ids:
                aluno_ocorrencia, aluno_created = Aluno_OcorrenciaAula.objects.get_or_create(
                    aluno_id=aluno_id,
                    ocorrenciaAula=ocorrencia
                )
                aluno_ocorrencia.presente = True  # Marcar a presença como verdadeira
                aluno_ocorrencia.save()

            return JsonResponse({'status': 'success'})

        except Aula.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'Aula não encontrada.'}, status=400)
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)}, status=400)

    return JsonResponse({'status': 'error', 'message': 'Método inválido.'}, status=400)

contact/views/alunos_views.py
from contact.models import *
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator
from django.conf import settings

def index(request):
    title = 'Aulas'

    # Obter as aulas do coach específico
    aulas = Aula.objects.filter(coach=1)
    alunos = alunos = Aluno.objects.all()

    # Paginar as aulas
    paginator = Paginator(aulas, 9)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    # Contexto atualizado para passar os alunos relacionados a cada aula
    context = {
        'title': title,
        'page_obj': page_obj,
        'alunos': alunos,
        'MEDIA_URL': settings.MEDIA_URL
    }

    return render(
        request,
        'tennisTracer/day.html',
        context,
    )



def profile(request, contact_id):
    title = 'Perfil'
    aluno = get_object_or_404(Aluno, pk=contact_id)
    # aluno = Aluno.objects.get(pk=contact_id)
    context = {
        'title': title,
        'aluno': aluno
    }

    return render(
        request, 
        'tennisTracer/profileCoach.html',
        context,
    )

# def profile(request):
#     title = 'Perfil'
#     aluno = get_object_or_404(Aluno, pk=contact_id)
#     # aluno = Aluno.objects.get(pk=contact_id)
#     context = {
#         'title': title,
#         'aluno': aluno
#     }

#     return render(
#         request, 
#         'tennisTracer/createdAluno.html',
#         context,
#     )

def profileCoach(request):
    title = 'Perfil'
    # aluno = get_object_or_404(Aluno, pk=contact_id)
    # aluno = Aluno.objects.get(pk=contact_id)
    context = {
        'title': title,
    }

    return render(
        request, 
        'tennisTracer/profileCoach.html',
        context,
    )

contact/templates/tennisTracer/create.html
{% extends "global/base.html" %}
{% block content %}

<h2 class="title"> Novo tema de Aula </h2>

    <form 
    action=" {% url "tennisTracer:create" %} " 
    method="POST"
    enctype="multipart/form-data" 
    >
        {% csrf_token %}
        
    
        <div class="form-content">
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {{ field.errors}}

                </div>
            {% endfor %}
        </div>
        
        <div class="btn">
            <button class="button-Card" type="submit">Enviar</button>
        </div>


    </form>

{% endblock content %}

contact/templates/tennisTracer/createAluno.html
{% extends "global/base.html" %}
{% block content %}

    <form 
    action=" {% url "tennisTracer:createAluno" %} " 
    method="POST"
    enctype="multipart/form-data" 
    >
        {% csrf_token %}
        
    
        <div class="form-content">
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {{ field.errors}}
                    {% if field.help_text %}
                        <p class="help-text"> 
                            {{field.help_text}}
                        </p>
                    {% endif %}
                </div>

            {% endfor %}
        </div>
        
        <div class="btn">
            <button class="button-Card" type="submit">Enviar</button>
        </div>


    </form>

{% endblock content %}

contact/templates/tennisTracer/createNotifications.html
{% extends "global/base.html" %} 

{% block content %}
<form 
    action=" {% url "tennisTracer:createTemas" %} " 
    method="POST"
    enctype="multipart/form-data" 
    >
        {% csrf_token %}
        
    
        <div class="form-content">
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {{ field.errors}}
                    {% if field.help_text %}
                        <p class="help-text"> 
                            {{field.help_text}}
                        </p>
                    {% endif %}
                </div>

            {% endfor %}
        </div>
        
        <div class="btn">
            <button class="button-Card" type="submit">Enviar</button>
        </div>


    </form>
{% endblock content%}

contact/templates/tennisTracer/createTemaAula.html
{% extends "global/base.html" %}
{% block content %}

    <form 
    action=" {% url "tennisTracer:createTemas" %} " 
    method="POST"
    enctype="multipart/form-data" 
    >
        {% csrf_token %}
        
    
        <div class="form-content">
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {{ field.errors}}
                    {% if field.help_text %}
                        <p class="help-text"> 
                            {{field.help_text}}
                        </p>
                    {% endif %}
                </div>

            {% endfor %}
        </div>
        
        <div class="btn">
            <button class="button-Card" type="submit">Enviar</button>
        </div>


    </form>

{% endblock content %}

contact/templates/tennisTracer/day.html
{% extends 'global/base.html' %} {% load static %} {% block content %}
  <main class="content">
    <div class="day">
      <div class="pagination-left">
        {% if page_obj.has_previous %}
          <a href="?page={{ page_obj.previous_page_number }}">&#9664;</a>
        {% else %}
          <span class="disabled">&#9664;</span>
        {% endif %}
      </div>
      <div class="nameDay">
        {% if page_obj %}
          <h1>{{ page_obj.object_list.0.day }}</h1>
        {% endif %}
      </div>
      <div class="pagination-right">
        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">&#9654;</a>
        {% else %}
          <span class="disabled">&#9654;</span>
        {% endif %}
      </div>
    </div>
    <div class="contentAula">
      {% for day in page_obj %}
        <div class="aula-Hora">
          <div class="card">
            <h1 class="title">{{ day.hora_ini }}</h1>
            <div class="aluno-Card">
              {% for person in day.aluno_aula_set.all %}
                <div class="aluno-Foto">
                  {% if person.aluno.picture %}
                    <img src="{{ person.aluno.picture.url }}" alt="{{ aluno.first_name }} {{ aluno.last_name }}" onerror="this.onerror=null; this.src='{{ MEDIA_URL }}pictures/defaults/default.png';" />
                  {% else %}
                    <!-- Adicione isso para ver o que está sendo renderizado -->
                    <img src="{{ MEDIA_URL }}pictures/defaults/default.png" alt="AAAA" />
                  {% endif %}
                  <div class="aluno-Nome">{{ person.aluno.last_name }}</div>
                </div>
              {% empty %}
                <p>Nenhum aluno inscrito nesta aula.</p>
              {% endfor %}
            </div>
            <div class="button">
              <button class="button-Card" onclick="openModal({{ day.id }}, '{{ day.hora_ini }}', '{{ day.day }}')">Adicionar Aluno</button>

              <button class="button-Card" onclick="openModalEndAula({{ day.id }}, '{{ day.hora_ini }}', '{{ day.day }}')">Finalizar Aula</button>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    {% comment %}MODAL DE ADD ALUNO{% endcomment %}
    <div id="myModal" class="modal">
      <div class="modal-content">
        <span class="close" onclick="closeModal()">&times;</span>
        <input type="hidden" id="aulaId" value="" />
        <h2 id="modalTitle" class="title">Adicionar Aluno à Aula</h2>
        <h5 class="subtitle">Escolha o Aluno</h5>

        <div class="alunos-modal">
          {% for aluno in alunos %}
            <a href="#" class="aluno-modal-one" onclick="vincularAluno({{ aluno.id }})">
              <div class="aluno-Foto-Modal">
                {% if aluno.picture %}
                  <img src="{{ aluno.picture.url }}" alt="{{ aluno.first_name }} {{ aluno.last_name }}" onerror="this.onerror=null; this.src='{{ MEDIA_URL }}pictures/defaults/default.png';" />
                {% else %}
                  <!-- Adicione isso para ver o que está sendo renderizado -->
                  <img src="{{ MEDIA_URL }}pictures/defaults/default.png" alt="AAAA" />
                {% endif %}
              </div>
              <div class="aluno-modal-one-name">
                {{ aluno.first_name }} <br />
                {{ aluno.last_name }}
              </div>
            </a>
          {% endfor %}
        </div>
      </div>
    </div>

    {% comment %}MODAL DE FINALIZAR A AULA{% endcomment %}
    <div id="FechaAula" class="modal" style="display: none;">
        <div class="modal-content-FinAula">
          <span class="close" onclick="closeModalEndAula()">&times;</span>
          <input type="hidden" id="aulaId" value="" />
      
          <h2 id="modalTitleEnd" class="title"></h2>
          <div class="centDate">
            <span class="subtitle">Selecione a Data: </span>
            <input type="date" id="data_ocorrencia" name="data_ocorrencia" required class="date" placeholder="DD/MM/AAAA">
          </div>
          <div id="alunosList" class="aluno-Card">
            <!-- Este conteúdo será preenchido dinamicamente via JS -->
          </div>
          <div class="buttonEnd">
            <button class="button-Modal-End" onclick="FinalizaAula()">Finalizar Aula</button>
          </div>
        </div>
      </div>
  </main>

<script>
    function closeModalEndAula() {
        document.getElementById('FechaAula').style.display = 'none'
      }
    
    function openModalEndAula(aulaId, hora_ini, day) {
        // Exibir o modal
        document.getElementById('FechaAula').style.display = 'block';
        document.getElementById('modalTitleEnd').innerText = `Finalizar Aula de ${day}, às ${hora_ini}`;
        // Limpar a lista de alunos atual
        var alunosList = document.getElementById('alunosList');
        alunosList.innerHTML = '';
      
        // Configurar o ID da aula no campo oculto
        document.getElementById('aulaId').value = aulaId;
      
        // Fazer uma requisição AJAX para buscar os alunos dessa aula
        fetch(`/tennisTracer/aula/${aulaId}/alunos/`)
          .then((response) => response.json())
          .then((data) => {
            if (data.alunos.length > 0) {
              // Populando o modal com os alunos
              data.alunos.forEach((aluno) => {
                var alunoDiv = `
                  <div class="aluno-Foto">
                    <img src="${aluno.picture || '/media/pictures/defaults/default.png'}" alt="${aluno.first_name} ${aluno.last_name}" />
                    <div class="aluno-Nome">${aluno.last_name}</div>
                    <!-- Adicionando a checkbox para vincular o aluno -->
                    <div class="aluno-checkbox">
                      <label>
                        <input type="checkbox" class="aluno-checkbox" name="alunos_vinculados" value='${aluno.id}' checked>
                      </label>
                    </div>
                  </div>
                `;
                alunosList.innerHTML += alunoDiv;
              });
            } else {
              alunosList.innerHTML = '<p>Nenhum aluno inscrito nesta aula.</p>';
            }
          })
          .catch((error) => console.error('Erro ao buscar os alunos:', error));
      }
      
      function FinalizaAula() {
        var aulaId = document.getElementById('aulaId').value;
        
        // Coletar os alunos que foram marcados como presentes
        var checkboxes = document.querySelectorAll('input[name="alunos_vinculados"]:checked');
        var alunosSelecionados = [];
        
        var dataOcorrencia = document.getElementById('data_ocorrencia').value;

    // Validar se uma data foi selecionada
        if (!dataOcorrencia) {
            alert('Por favor, selecione a data da aula.');
            return;
        }
        
        checkboxes.forEach((checkbox) => {
          alunosSelecionados.push(checkbox.value);
        });
      
        // Enviar os dados dos alunos selecionados
        var data = {
          aula_id: aulaId,
          alunos: alunosSelecionados,
          data_ocorrencia: dataOcorrencia
        };
      
        fetch('/tennisTracer/aula/presente/', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}' // Inclua o CSRF token
          },
          body: JSON.stringify(data)
        })
        .then((response) => response.json())
        .then((data) => {
          if (data.status === 'success') {
            alert('Presença registrada com sucesso!');
            closeModal();
          } else {
            alert('Erro ao salvar a presença.');
          }
        })
        .catch((error) => console.error('Erro ao salvar a presença:', error));
      }

      function openModal(id, hora_ini, day) {
        document.getElementById('myModal').style.display = 'block'
      
        document.getElementById('modalTitle').innerText = 'Adicionar Aluno à Aula ' + day + ' às ' + hora_ini
        document.getElementById('aulaId').value = id
      }
      function closeModal() {
        document.getElementById('myModal').style.display = 'none'
      }
      
      function vincularAluno(alunoId) {
        var aulaId = document.getElementById('aulaId').value
      
        // Configurar os dados para enviar
        var data = {
          aula_id: aulaId,
          aluno_id: alunoId
        }
      
        // Enviar a requisição POST
        fetch('/tennisTracer/vinAluno/', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}' // Inclua o CSRF token
          },
          body: JSON.stringify(data)
        })
          .then((response) => response.json())
          .then((data) => {
            if (data.status === 'success') {
              // Exibir mensagem de sucesso
              alert('Aluno vinculado com sucesso!')
              // Fechar o modal e recarregar a página ou redirecionar
              closeModal()
              window.location.href = '/tennisTracer/'
            } else if (data.status === 'duplicate') {
              alert('Este aluno já está vinculado a esta aula.')
            } else {
              alert('Erro ao vincular aluno.')
            }
          })
          .catch((error) => console.error('Erro:', error))
      }
</script>
{% endblock %}

contact/templates/tennisTracer/list_aulas.html
{% extends "global/base.html" %}

{% block content %}
    {% for aula in aulas %}
        
    {% endfor %}
{% endblock content %}

contact/templates/tennisTracer/profileCoach.html
{% extends "global/base.html" %} 

{% block content %}

<div class="text-coach">
    <h1 class="title-coach">Olá Coach!</h1>
    <h2 class="subtitle-coach">Ações:</h2> 
</div>

<ul class="menu-list-Coach">
    <li class="menu-Coach">
        <a href= " {% url 'tennisTracer:createAluno' %} " class="menu-link-coach">
            <i class="fas fa-user-plus"></i>
            <span>Novo Aluno</span>
        </a>
    </li>
    <li class="menu-Coach">
        <a href= " {% url 'tennisTracer:index' %} " class="menu-link-coach">
            <i class="fas fa-plus-square"></i> 
            <span>Aulas</span>
        </a>
    </li>
    <li class="menu-Coach">
        <a href= " {% url 'tennisTracer:createTemas' %} " class="menu-link-coach">
            <i class="fas fa-calendar-check"></i> 
            <span>Aulas</span>
        </a>
    </li>
</ul>

{% endblock content %}